spring:
    jdbc:
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:test
        username: root
        password: abc123
    profiles:
      active: jdbc